INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_SATELLITEMODEM SatelliteModem)

FIND_PATH(
    SATELLITEMODEM_INCLUDE_DIRS
    NAMES SatelliteModem/api.h
    HINTS $ENV{SATELLITEMODEM_DIR}/include
        ${PC_SATELLITEMODEM_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    SATELLITEMODEM_LIBRARIES
    NAMES gnuradio-SatelliteModem
    HINTS $ENV{SATELLITEMODEM_DIR}/lib
        ${PC_SATELLITEMODEM_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SATELLITEMODEM DEFAULT_MSG SATELLITEMODEM_LIBRARIES SATELLITEMODEM_INCLUDE_DIRS)
MARK_AS_ADVANCED(SATELLITEMODEM_LIBRARIES SATELLITEMODEM_INCLUDE_DIRS)

